### ISSUE TITLE
Cannot invoke multiple script providers with different environment variables

### ISSUE THREAD

**Issue by rafael-nogueras** [18F/cf-blue-green#31]
I have found your script really useful because of its integration with Travis (which other projects like Autopilot seem to be lacking), so first of all, thanks!

I am trying to use your script to deploy the same code to several Cloud Foundry apps; thus, I find myself wanting to create multiple `script` provider blocks, each with its own value of `CF_APP`, like so:

```
deploy:
    - provider: script
      skip_cleanup: true
      script: cf-blue-green-travis
      env:
        CF_APP: [NAME OF FIRST APP]
      on:
        branch:
        - development
    - provider: script
      skip_cleanup: true
      script: cf-blue-green-travis
      env:
        CF_APP: [NAME OF SECOND APP]
      on:
        branch:
        - development
env:
  global:
    - CF_API=[MY API ENDPOINT]
    - CF_ORGANIZATION=[MY ORGANIZATION]
    - CF_SPACE=[MY SPACE]
```

   However, that does not seem to work: when your script runs, it always behaves as though `CF_APP` were not defined. Is that a limitation on Travis's part, or is there a way to have your script allow deployment to several apps (perhaps in different organizations or spaces, too)?

Thanks for your time!
